export const types = {
    LOGIN:'LOGIN',
    LOGOUT: 'LOGUT',
    RETURN_EQUAL_AUTH: 'RETURN_EQUAL_AUTH',
    ADD_HABITO:'ADD_HABITO',
    UPDATE_HABITO: 'UPDATE_HABITO',
    DELETE_HABITO: 'DELETE_HABITO',
    RETURN_HABITO: 'RETURN_HABITO',
    TITULO_HABITO: 'TITULO_HABITO',
    ORDENAR_FECHA_HABITO: 'ORDENAR_FECHA_HABITO',
    ORDENAR_HOY_HABITO: 'ORDENAR_HOY_HABITO',
    ORDENAR_DIFICULTAD_HABITO: 'ORDENAR_DIFICULTAD_HABITO',
    RETURN_MISIONES: 'RETURN_MISIONES',
    AGREGAR_ESTUDIANTE: 'AGREGAR_ESTUDIANTE',
    TERMINAR_MISION: 'TERMINAR_MISION'

};